### PR TITLE
feat: Fixes issue #378: ✨ Add support for single day & full day recurring events

### LINKED ISSUE #378: Need support for events that occurs on specific weekday every week.
Assuming there is an event that is to repeat for specific days 

ex : going to the gym ( Sunday, Monday, Wednesday ) weekly.

How can I display the event in the month view ?

### PR DESCRIPTION
**Pull request by shubham-jitiya-simform**
# Description

1. Added support in month view, day view & week view .
2. Supported repeat modes: Do no repeat, daily, weekly, monthly & yearly.
3. Supported recurrence end: Never, on given date & till given interval.
4. Edit will apply to all repeating events.
5. Deletes a recurring event based on the specified deletion type: Current, Following, All occurrence.
6. Support for ranging events are not added due to open issues: #23 

# Preview
## Repeat: Do not repeat
| Image 1 |
|:--:|
| Do not repeat |

## Repeat: Daily
| Image 1 | Image 2 | Image 3 |
|:--:|:--:|:--:|
| Repeat: Daily - Ends on: Never | Repeat: Daily - Ends on: specified date | Repeat: Daily - Ends on: Specified Interval |

## Repeat: Weekly
| Weekly Never | Weekly Never with Specific Weeks | Weekly Ends On | Weekly Occurrence |
|:--:|:--:|:--:|:--:|
| Repeat end: never | Select specific weeks to repeat | Select end date to repeat | Repeat specific times |

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have followed the [Contributor Guide] when preparing my PR.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [x] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [x] Yes, this PR is a breaking change.
- [ ] No, this PR is not a breaking change.

## Related Issues

Closes #378 

[Contributor Guide]: https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/blob/master/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

File: lib/src/month_view/month_view.dart [hunk 1]
```diff
@@ -721,7 +721,7 @@ class _MonthPageBuilder<T> extends StatelessWidget {
         itemBuilder: (context, index) {
           // Hide events if `hideDaysNotInMonth` true
           final events =
-              hideDaysNotInMonth & (monthDays[index].month != date.month)
+              hideDaysNotInMonth && (monthDays[index].month != date.month)
```
Comment (PRBaraiya) [inline lib/src/month_view/month_view.dart:724]: What's the reason for changing this?

File: lib/src/event_controller.dart [hunk 2]
```diff
@@ -73,7 +71,73 @@ class EventController<T extends Object?> extends ChangeNotifier {
 
   //#endregion
 
+  //#region Private Methods
```
Comment (PRBaraiya) [inline lib/src/event_controller.dart:74]: Helper / Private methods must be at the end of the class.

File: lib/src/event_controller.dart [hunk 3]
```diff
@@ -216,17 +289,22 @@ class CalendarData<T extends Object?> {
...
   UnmodifiableListView<CalendarEventData<T>> get fullDayEventList =>
       UnmodifiableListView(_fullDayEventList);
+  //#endregion
 
   //#region Data Manipulation Methods
   void addFullDayEvent(CalendarEventData<T> event) {
     // TODO: add separate logic for adding full day event and ranging event.
     _fullDayEventList.addEventInSortedManner(event, _eventSorter);
-    _eventList.add(event);
+    event.recurrenceSettings == null
```
Comment (PRBaraiya) [inline lib/src/event_controller.dart:298]: This will add event in _fullDayEventList as well as _reccurringEventsList. Which will create duplication.

File: lib/src/event_controller.dart [hunk 4]
```diff
@@ -216,17 +289,22 @@ class CalendarData<T extends Object?> {
...
+        ? _eventList.add(event)
+        : _recurringEventsList.add(event);
   }
 
   void addRangingEvent(CalendarEventData<T> event) {
     _rangingEventList.addEventInSortedManner(event, _eventSorter);
-    _eventList.add(event);
+    event.recurrenceSettings == null
```
Comment (PRBaraiya) [inline lib/src/event_controller.dart:305]: ^^

File: lib/src/event_controller.dart [hunk 5]
```diff
@@ -240,16 +318,18 @@ class CalendarData<T extends Object?> {
       _singleDayEvents[date]!.addEventInSortedManner(event, _eventSorter);
     }
 
-    _eventList.add(event);
+    event.recurrenceSettings == null
```
Comment (PRBaraiya) [inline lib/src/event_controller.dart:321]: ^^

File: lib/src/event_controller.dart [hunk 6]
```diff
@@ -240,16 +318,18 @@ class CalendarData<T extends Object?> {
...
   }
 
   void addEvent(CalendarEventData<T> event) {
     assert(event.endDate.difference(event.date).inDays >= 0,
         'The end date must be greater or equal to the start date');
 
     // TODO: improve this...
-    if (_eventList.contains(event)) return;
-
+    if (_eventList.contains(event) || _recurringEventsList.contains(event))
```
Comment (PRBaraiya) [inline lib/src/event_controller.dart:331]: No need to check event in _recurringEventsList.

File: lib/src/event_controller.dart [hunk 7]
```diff
@@ -261,19 +341,25 @@ class CalendarData<T extends Object?> {
...
+      event.recurrenceSettings == null
+          ? _eventList.remove(event)
+          : _recurringEventsList.remove(event);
     }
   }
 
   void removeSingleDayEvent(CalendarEventData<T> event) {
     if (_singleDayEvents[event.date]?.remove(event) ?? false) {
-      _eventList.remove(event);
+      event.recurrenceSettings == null
```
Comment (PRBaraiya) [inline lib/src/event_controller.dart:360]: we should be able to remove this in every place as well.

**Review by PRBaraiya — CHANGES_REQUESTED** [review]

File: lib/src/month_view/month_view.dart (hunk 1 above)
Comment (shubham-jitiya-simform) [reply lib/src/month_view/month_view.dart:724]: While fixing issue to hide events list in cell if "hide days not in month" is true in PR #422 by mistake bitwise operator `&` is used instead of `&&` AND operator.

File: lib/src/event_controller.dart (hunk 3 above)
Comment (shubham-jitiya-simform) [reply lib/src/event_controller.dart:298]: Removed add recurring event in each method addFullDayEvent, addSingleDayEvent & addRangingEvent.

File: lib/src/event_controller.dart [hunk 8]
```diff
@@ -52,14 +50,18 @@ class EventController<T extends Object?> extends ChangeNotifier {
...
   ///
-  /// NOTE: This field is deprecated. use [allEvents] instead.
+  /// NOTE: This field is deprecated. use [nonRecurringEvents] instead.
   List<CalendarEventData<T>> get events =>
       _calendarData.events.toList(growable: false);
 
-  /// Lists all the events that are added in the Controller.
-  UnmodifiableListView<CalendarEventData<T>> get allEvents =>
+  /// Lists all the non-recurring events that are added in the Controller.
+  UnmodifiableListView<CalendarEventData<T>> get nonRecurringEvents =>
```
Comment (PRBaraiya) [inline lib/src/event_controller.dart:58]: can we keep this as allEvents.

File: lib/src/event_controller.dart [hunk 9]
```diff
@@ -250,6 +330,13 @@ class CalendarData<T extends Object?> {
     // TODO: improve this...
     if (_eventList.contains(event)) return;
 
+    // Recurring event
+    if (event.isRecurringEvent) {
+      _recurringEventsList.add(event);
```
Comment (PRBaraiya) [inline lib/src/event_controller.dart:335]: This should add event in _eventList as well.

File: lib/src/event_controller.dart [hunk 10]
```diff
@@ -52,14 +50,18 @@ class EventController<T extends Object?> extends ChangeNotifier {
...
       _calendarData.events.toList(growable: false);
 
-  /// Lists all the events that are added in the Controller.
-  UnmodifiableListView<CalendarEventData<T>> get allEvents =>
+  /// Lists all the non-recurring events that are added in the Controller.
+  UnmodifiableListView<CalendarEventData<T>> get nonRecurringEvents =>
       _calendarData.events;
 
+  /// Lists all the recurring events that are added in the Controller.
+  UnmodifiableListView<CalendarEventData<T>> get recurringEvents =>
```
Comment (PRBaraiya) [inline lib/src/event_controller.dart:62]: Let not add this. It will create confusion.

**Review by PRBaraiya — CHANGES_REQUESTED** [review]

**Review by PRBaraiya — APPROVED** [review]
LGTM!
