### PR TITLE
Fix/issue 391 manuly update scroll offset

### LINKED ISSUE #391: Manually update the weekView scrollOffset
Currently using `scrollOffset` we cannot programmatically update the scroll Position

### PR DESCRIPTION
**Pull request by bawantha**
# Description

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have followed the [Contributor Guide] when preparing my PR.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [ ] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [x] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues

[Contributor Guide]: https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/blob/master/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

**Review by ParthBaraiya — APPROVED** [review]

File: lib/src/week_view/week_view.dart [hunk 1]
```diff
@@ -462,6 +462,11 @@ class WeekViewState<T extends Object?> extends State<WeekView<T>> {
 
     // Update builders and callbacks
     _assignBuilders();
+
+    if (widget.scrollOffset != oldWidget.scrollOffset) {
+      _lastScrollOffset = widget.scrollOffset;
```
Comment (ParthBaraiya) [inline lib/src/week_view/week_view.dart:467]: This line should be like following,

 _lastScrollOffset = widget.scrollOffset ??
        widget.startDuration.inMinutes * widget.heightPerMinute;

**Review by ParthBaraiya — CHANGES_REQUESTED** [review]

**Review by PRBaraiya — APPROVED** [review]
LGTM!
