### PR TITLE
fix: 🐛 Event till 12 am

### LINKED ISSUE #161: Unable to add 11.30 PM to 12.00PM
Am unable to add these time. Please resolved it.

### PR DESCRIPTION
**Pull request by faiyaz-shaikh**
# Description
Event till 12 am

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have followed the [Contributor Guide] when preparing my PR.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [ ] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues
Fixes #161 

[Contributor Guide]: https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/blob/master/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

File: lib/src/event_arrangers/side_event_arranger.dart [hunk 1]
```diff
@@ -87,7 +89,11 @@ class SideEventArranger<T extends Object?> extends EventArranger<T> {
           left: slotWidth * (sideEvent.column - 1),
           right: slotWidth * (column - sideEvent.column),
           top: startTime.getTotalMinutes * heightPerMinute,
-          bottom: height - endTime.getTotalMinutes * heightPerMinute,
+          bottom: height -
+              (endTime.getTotalMinutes == 0
```
Comment (DhvanitVaghani) [inline lib/src/event_arrangers/side_event_arranger.dart:93]: You can make one variable to pass the bottom parameter. Write all condition on that variable

**Review by DhvanitVaghani — APPROVED** [review]

**Review by DhvanitVaghani — APPROVED** [review]

**Review by ShwetaChauhan18 — APPROVED** [review]
