### PR TITLE
fix: 🐛hide month days not in current month functionality added #328.

### LINKED ISSUE #328: Hide days from previois and next month in month view
In the month view, I want to display the days only for the current month. I don't want to display the last days from the previous month and the first days from the next month.
Thank you.

### PR DESCRIPTION
**Pull request by apurva010**
# Description
- hideDayNotInMonth added. It by default false. It set to true to hide date which not is in current month.

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have followed the [Contributor Guide] when preparing my PR.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [x] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues

Closes #328 

[Contributor Guide]: https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/blob/master/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

File: lib/src/components/month_view_components.dart [hunk 1]
```diff
@@ -133,22 +137,24 @@ class FilledCell<T extends Object?> extends StatelessWidget {
...
-                    ? highlightedTitleColor
-                    : isInMonth
-                        ? titleColor
-                        : titleColor.withOpacity(0.4),
-                fontSize: 12,
-              ),
-            ),
-          ),
+          (!isInMonth && hideDaysNotInMonth)
+              ? SizedBox.shrink()
```
Comment (vatsaltanna) [inline lib/src/components/month_view_components.dart:141]: we can remove the ternary condition.

**Review by vatsaltanna-simformsolutions — APPROVED** [review]
